#!/bin/sh
mkdir -p /app/live/cam1 /app/live/cam2 /app/live/cam3 /app/live/cam4 /app/live/cam5 /app/live/cam6 /app/live/cam7 /app/live/cam8 /app/live/cam9 /app/live/cam10 /app/live/cam11 /app/live/cam12 /app/live/cam13 /app/live/cam14

# Resimi indir
curl -L -o /app/aksaray.jpg https://raw.githubusercontent.com/ahmetdogan68/iptv/d135617ff207d7bab17766e797769338b7b311f7/aksaray.jpg

# 5 TANE KAMERALI - Senin asıl istediklerin
ffmpeg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30 -i "https://kamerayayin.ibb.istanbul/turistikcam/anadoluhisari.stream/playlist.m3u8" -i "https://stream.turkiyeradyolari.com:8100/stream" -map 0:v:0 -map 1:a:0 -c:v copy -c:a aac -b:a 96k -f hls -hls_time 6 -hls_list_size 10 -hls_flags delete_segments+append_list /app/live/cam1/playlist.m3u8 &
ffmpeg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30 -i "https://kamerayayin.ibb.istanbul/turistikcam/beyazitkulesi2.stream/playlist.m3u8" -i "https://radyo.yayindakiler.com:4036/" -map 0:v:0 -map 1:a:0 -c:v copy -c:a aac -b:a 96k -f hls -hls_time 6 -hls_list_size 10 -hls_flags delete_segments+append_list /app/live/cam2/playlist.m3u8 &
ffmpeg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30 -i "https://kamerayayin.ibb.istanbul/turistikcam/sarachane.stream/playlist.m3u8" -i "https://stream.turkiyeradyolari.com:9332/stream" -map 0:v:0 -map 1:a:0 -c:v copy -c:a aac -b:a 96k -f hls -hls_time 6 -hls_list_size 10 -hls_flags delete_segments+append_list /app/live/cam3/playlist.m3u8 &
ffmpeg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30 -i "https://kamerayayin.ibb.istanbul/turistikcam/taksim.stream/playlist.m3u8" -i "https://radyo.yayindakiler.com:4022/" -map 0:v:0 -map 1:a:0 -c:v copy -c:a aac -b:a 96k -f hls -hls_time 6 -hls_list_size 10 -hls_flags delete_segments+append_list /app/live/cam4/playlist.m3u8 &
ffmpeg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30 -i "https://kamerayayin.ibb.istanbul/turistikcam/pierreloti.stream/playlist.m3u8" -i "https://radyo.yayindakiler.com:4026/" -map 0:v:0 -map 1:a:0 -c:v copy -c:a aac -b:a 96k -f hls -hls_time 6 -hls_list_size 10 -hls_flags delete_segments+append_list /app/live/cam5/playlist.m3u8 &

# 9 TANE RESIMLI - Cok hafif, yer kaplamaz
ffmpeg -loop 1 -framerate 1 -i /app/aksaray.jpg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30 -i "https://moondigitaledge.radyotvonline.net/turkulerleturkiye/playlist.m3u8" -map 0:v:0 -map 1:a:0 -c:v libx264 -r 2 -pix_fmt yuv420p -vf scale=1280:720 -c:a aac -b:a 96k -shortest -f hls -hls_time 6 -hls_list_size 10 -hls_flags delete_segments+append_list /app/live/cam6/playlist.m3u8 &
ffmpeg -loop 1 -framerate 1 -i /app/aksaray.jpg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30 -i "https://yayin.turkhosted.com/4591/stream" -map 0:v:0 -map 1:a:0 -c:v libx264 -r 2 -pix_fmt yuv420p -vf scale=1280:720 -c:a aac -b:a 96k -shortest -f hls -hls_time 6 -hls_list_size 10 -hls_flags delete_segments+append_list /app/live/cam7/playlist.m3u8 &
ffmpeg -loop 1 -framerate 1 -i /app/aksaray.jpg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30 -i "https://rd-trtturku.medya.trt.com.tr/master_128.m3u8" -map 0:v:0 -map 1:a:0 -c:v libx264 -r 2 -pix_fmt yuv420p -vf scale=1280:720 -c:a aac -b:a 96k -shortest -f hls -hls_time 6 -hls_list_size 10 -hls_flags delete_segments+append_list /app/live/cam8/playlist.m3u8 &
ffmpeg -loop 1 -framerate 1 -i /app/aksaray.jpg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30 -i "https://moondigitaledge2.radyotvonline.net/radyo7turku/playlist.m3u8" -map 0:v:0 -map 1:a:0 -c:v libx264 -r 2 -pix_fmt yuv420p -vf scale=1280:720 -c:a aac -b:a 96k -shortest -f hls -hls_time 6 -hls_list_size 10 -hls_flags delete_segments+append_list /app/live/cam9/playlist.m3u8 &
ffmpeg -loop 1 -framerate 1 -i /app/aksaray.jpg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30 -i "https://moondigitaledge2.radyotvonline.net/radyo7muhtesem4lu/playlist.m3u8" -map 0:v:0 -map 1:a:0 -c:v libx264 -r 2 -pix_fmt yuv420p -vf scale=1280:720 -c:a aac -b:a 96k -shortest -f hls -hls_time 6 -hls_list_size 10 -hls_flags delete_segments+append_list /app/live/cam10/playlist.m3u8 &
ffmpeg -loop 1 -framerate 1 -i /app/aksaray.jpg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30 -i "https://moondigitaledge2.radyotvonline.net/radyo7nostalji/playlist.m3u8" -map 0:v:0 -map 1:a:0 -c:v libx264 -r 2 -pix_fmt yuv420p -vf scale=1280:720 -c:a aac -b:a 96k -shortest -f hls -hls_time 6 -hls_list_size 10 -hls_flags delete_segments+append_list /app/live/cam11/playlist.m3u8 &
ffmpeg -loop 1 -framerate 1 -i /app/aksaray.jpg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30 -i "https://moondigitaledge2.radyotvonline.net/radyo7ankara/playlist.m3u8" -map 0:v:0 -map 1:a:0 -c:v libx264 -r 2 -pix_fmt yuv420p -vf scale=1280:720 -c:a aac -b:a 96k -shortest -f hls -hls_time 6 -hls_list_size 10 -hls_flags delete_segments+append_list /app/live/cam12/playlist.m3u8 &
ffmpeg -loop 1 -framerate 1 -i /app/aksaray.jpg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30 -i "https://moondigitaledge.radyotvonline.net/radyo7/playlist.m3u8" -map 0:v:0 -map 1:a:0 -c:v libx264 -r 2 -pix_fmt yuv420p -vf scale=1280:720 -c:a aac -b:a 96k -shortest -f hls -hls_time 6 -hls_list_size 10 -hls_flags delete_segments+append_list /app/live/cam13/playlist.m3u8 &
ffmpeg -loop 1 -framerate 1 -i /app/aksaray.jpg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30 -i "https://moondigitaledge2.radyotvonline.net/radyo7arabesk/playlist.m3u8" -map 0:v:0 -map 1:a:0 -c:v libx264 -r 2 -pix_fmt yuv420p -vf scale=1280:720 -c:a aac -b:a 96k -shortest -f hls -hls_time 6 -hls_list_size 10 -hls_flags delete_segments+append_list /app/live/cam14/playlist.m3u8 &

python3 -m http.server 10000 --directory /app/live
