name: M3U Guncelle
permissions:
  contents: write
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python converter.py
      - run: |
          git config user.name "aksaray-bot"
          git config user.email "bot@aksaray.com"
          git add playlist.m3u
          git commit -m "m3u guncellendi" || exit 0
          git push
