name: M3U Guncelle
permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Kutuphaneleri yukle
        run: pip install requests
      - name: m3u olustur
        run: python converter.py
      - name: GitHub'a kaydet
        run: |
          git config user.name "aksaray-bot"
          git config user.email "bot@aksaray.com"
          git add playlist.m3u
          git commit -m "m3u guncellendi" || exit 0
          git push
